config/routes.rb
Rails.application.routes.draw do

  resources :convocations do
    member do 
      get  'cargar-postulaciones'    => 'convocations#cargar_postulaciones',              as: 'carga_postulaciones'
      post 'importar-postulaciones' => 'convocations#importar_postulaciones',            as: 'import_applications'
      get  'exportar-prepostulantes' => 'convocations#exportar_prepostulantes',           as: 'exportar_prepostulantes'
      get  'ipe/html'                => 'convocations#html_prepostulantes_evaluados',     as: 'html_prepostulantes_evaluados'
      post 'ipe'                     => 'convocations#importar_prepostulantes_evaluados', as: 'importar_prepostulantes_evaluados'
      get "make"       => "convocations#make_draw", as: 'make_draw'
      get "results"    => "convocations#results"
      post 'sendmails' => 'convocations#send_mails'  
      post 'sendorganizationsmails' => 'convocations#send_mails_to_organizations'
    end
    collection do 
      get 'findapplications' => 'convocations#find_applications'
      post 'make'            => 'convocations#make_draw!'
    end
  end

  devise_for :users
  root to: "dashboard#index"

  get 'beneficiarios/:id' => 'applications#carta_beneficiario', as: :carta_beneficiario

  get 'convocations/:id/organization/:id_empresa' => 'convocations#carta_empresa', as: :carta_empresa

  resources :applications do
    collection do
      get 'full' => 'applications#full', as: 'full_application'
    end
  end

  resources :organizations

  resources :applicants do
    collection do
      post :import
    end
  end

  resources :departaments

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div><h1> Acceso directo </h1></div>
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingZero">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseZero" aria-expanded="true" aria-controls="collapseZero">
          Nueva Convocatoria
        </a>
      </h4>
    </div>
    <div id="collapseZero" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingZero">
      <div class="panel-body">
        <%= link_to ' Crear convocatoria', new_convocation_path, class: 'fa fa-folder-open' %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Nuevo Postulante
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%= link_to ' Nuevo Postulante', new_applicant_path, class: 'fa fa-user' %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Nueva Empresa
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <%= link_to ' Nueva Empresa', new_organization_path, class: 'fa fa-building-o' %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Nueva Postulacion
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <%= link_to ' Nueva Postulacion', new_application_path, class: 'fa fa-inbox'  %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
         Importar archivo de Postulantes
        </a>
      </h4>
    </div>

    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
          <%= form_tag import_applicants_path, multipart: true do %>
    <label class="btn btn-default btn-file">
      Elegir archivo<%= file_field_tag :file, class: 'hidden' %>
    </label>
    <%= submit_tag "Importar", class: 'btn btn-success' %>
  <% end %>
      </div>
    </div>
  </div>
    <!--<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
         Importar archivo de Postulaciones
        </a>
      </h4>
    </div>

    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
          <%#= form_tag import_applications_path, multipart: true do %>
    <label class="btn btn-default btn-file">
      Elegir archivo<%#= file_field_tag :file, class: 'hidden' %>
    </label>
    <%#= submit_tag "Importar", class: 'btn btn-success' %>
  <%# end %>
      </div>
    </div>-->
  </div>


</div>