config/routes.rb
Rails.application.routes.draw do

  resources :convocations do
    member do 
      get  'cargar-postulaciones'    => 'convocations#cargar_postulaciones',              as: 'carga_postulaciones'
      post 'importar-postulaciones' => 'convocations#importar_postulaciones',            as: 'import_applications'
      get  'exportar-prepostulantes' => 'convocations#exportar_prepostulantes',           as: 'exportar_prepostulantes'
      get  'ipe/html'                => 'convocations#html_prepostulantes_evaluados',     as: 'html_prepostulantes_evaluados'
      post 'ipe'                     => 'convocations#importar_prepostulantes_evaluados', as: 'importar_prepostulantes_evaluados'
      get "make"       => "convocations#make_draw", as: 'make_draw'
      get "results"    => "convocations#results"
      post 'sendmails' => 'convocations#send_mails'  
      post 'sendorganizationsmails' => 'convocations#send_mails_to_organizations'
    end
    collection do 
      get 'findapplications' => 'convocations#find_applications'
      post 'make'            => 'convocations#make_draw!'
    end
  end

  devise_for :users
  root to: "dashboard#index"

  get 'beneficiarios/:id' => 'applications#carta_beneficiario', as: :carta_beneficiario

  get 'convocations/:id/organization/:id_empresa' => 'convocations#carta_empresa', as: :carta_empresa

  resources :applications do
    collection do
      get 'full' => 'applications#full', as: 'full_application'
    end
  end

  resources :organizations

  resources :applicants do
    collection do
      post :import
    end
  end

  resources :departaments

end

app/models/convocation.rb
  # == Schema Information
#
# Table name: convocations
#
#  id                  :integer          not null, primary key
#  fecha_limite        :date
#  fecha_inicio        :date
#  nombre              :string(50)
#  created_at          :datetime
#  updated_at          :datetime
#  sorteo_realizado_el :date
#

class Convocation < ActiveRecord::Base

  has_many :applications
  accepts_nested_attributes_for :applications 

  has_many :convocation_organizations
  has_many :organizations, through: :convocation_organizations

  validates_presence_of :nombre, :fecha_inicio, :fecha_limite

  ABIERTA               = "ABIERTA"
  EVALUACION_MINISTERIO = "EVALUACION_MINISTERIO"
  EVALUADA              = "EVALUADA"
  CERRADA               = "CERRADA"

  ESTADOS = [ABIERTA, EVALUACION_MINISTERIO, EVALUADA, CERRADA]

   def sortear!
    adjudicados = []
    rechazados = []
    Convocation.transaction do    
      organizations.order(cantidad_personal: :desc).each do |org| 
        vacantes = org.vacantes
        #busco las postulaciones a esta empresa
        post_en_esta_org = applications.where(organization: org, 
                                              estado: Application::ACEPTADO)
                                        .shuffle
                                        .shuffle
        vacantes.times do |i|
          postulacion = post_en_esta_org[i]
          #en el hipotético caso en el que hayan más vacantes que postulaciones
          #la siguiente postulacion puede no existir
          if postulacion
            #byebug
            postulacion.update(estado: Application::ASIGNADO)
            adjudicados << postulacion
          end
        end
      end
      adjudicados_ids = adjudicados.map { |a| a.id }
      rechazados = applications.where.not(id: adjudicados_ids)
      rechazados.each { |r| r.update(estado: Application::NO_ASIGNADO) }
      update(estado: CERRADA, sorteo_realizado_el: Date.today)
    end
    {adjudicados: adjudicados, rechazados: rechazados}
  end

  def results
    adjudicados = []
    rechazados = []
    applications.each do |a|
      adjudicados << a if a.adjudicado?
      rechazados << a if a.no_asignado?
    end
    {adjudicados: adjudicados, rechazados: rechazados}
  end

  def to_s
    "#{nombre}. Fecha inicio: #{fecha_inicio}, fecha límite: #{fecha_limite}"
  end

  def important_data
    "#{nombre}"
  end

  def algun_beneficiario_asignado?(organization)
    results[:adjudicados].each do |adj|
      return true if adj.organization == organization
    end
    false
  end

  def adjudicados_of(organization)
    adjs = []
    results[:adjudicados].each do |adj|
      adjs << adj if adj.organization == organization
    end
    adjs
  end

  def importar_prepostulantes_evaluados(excel)
    workbook = RubyXL::Parser.parse(excel.path)
    primero = true
    workbook[0].each do |row|
      next if row.nil?
      if primero 
        primero = false
        next
      end
      application = Application.joins(:applicant).where(applicants: {cuil: row[1].value.gsub("-","")}).take
      if application
        application.set_estado_desde_codigo(row[3].value.to_i)
        application.save!
      end
    end
    update(estado: EVALUADA)
  end

  def empresas_con_adjudicaciones
    organizations.select {|o| algun_beneficiario_asignado?(o)}
  end

  def sorteo_realizado?
    sorteo_realizado_el  
  end


  def estado_to_human
    case estado
    when EVALUACION_MINISTERIO  
      "En evaluación por el ministerio"
    else
      estado.capitalize unless estado.nil?
    end
  end

  def cerrada?
    estado == CERRADA
  end

end

app/controllers/convocations_controller.rb
class ConvocationsController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:send_mails, :send_mails_to_organizations, :make_draw, :make!, :carta_empresa]
  skip_before_filter :verify_authenticity_token, only: [:send_mails, :carta_beneficiario, :carta_empresa, :make!, :make_draw, :carta_beneficiario]

  before_action :set_convocation, only: [:show, 
                                         :edit, 
                                         :update, 
                                         :destroy, 
                                         :importar_postulaciones, 
                                         :importar_prepostulantes_evaluados,
                                         :cargar_postulaciones, 
                                         :exportar_prepostulantes, 
                                         :html_prepostulantes_evaluados,
                                         :make_draw!,
                                         :results,
                                         :send_mails,
                                         :find_applications,
                                         :make_draw, 
                                         :send_mails_to_organizations]


  respond_to :html

#--CRUD ACTIONS

  def index
    @convocations = Convocation.all.paginate(:page => params[:page], :per_page => 15)
    respond_with(@convocations)
  end

  def show
    respond_with(@convocation)
  end

  def new
    @convocation = Convocation.new
    respond_with(@convocation)
  end

  def edit
  end

  def create
    @convocation = Convocation.new(convocation_params)
    @convocation.save
    respond_with(@convocation)
  end

  def update
    @convocation.update(convocation_params)
    respond_with(@convocation)
  end

  def destroy
    @convocation.destroy
    respond_with(@convocation)
  end

#--CRUD ACTIONS

  def make_draw!
    if @convocation.sorteo_realizado?
      render json: "Sorteo ya realizado", status: :unprocessable_entity
    else
      @resultados = @convocation.sortear!
      render json: resultados_as_json, status: :ok
    end
  end

  def make_draw
    if @convocation.cerrada?
      @error   = true
      @message = "Esta convocatoria ya está cerrada"
    end
  end

  def results
    @resultados = @convocation.results
  end

  def send_mails
    if Rails.env.development?
      DrawMailer.mail_adjudicado(@convocation.where(estado: Application::ASIGNADO).first).deliver!
    end
    if Rails.env.production?
      @convocation.results[:adjudicados].each { |adj| DrawMailer.mail_adjudicado(adj).deliver! }
    end
    render json: {}, status: :ok
  end

  def send_mails_to_organizations
    byebug
    @convocation.organizations.each do |org|
      if @convocation.algun_beneficiario_asignado?(org)
        DrawMailer.mail_empresas(org, @convocation.adjudicados_of(org), @convocation).deliver!
      end
    end
    render json: {}, status: :ok
  end

  def find_applications
    render json: @convocation.applications, status: :ok
  end

  def cargar_postulaciones
    render :carga_postulaciones
  end

  def carta_empresa
    @org = Organization.find(params[:id_empresa])
    @convocation = Convocation.find(params[:id])
    render 'letters/empresa', layout: false, status: :ok
  end

  def importar_postulaciones
    if @convocation.cerrada?
      @error   = true
      @message = "La convocatoria ha sido cerrada ya"
      render :index and return
    end
    if params[:file]
      Application.import(params[:file], @convocation)
      render "applications/import_finished"
    else
      render "applicants/import_fail"
    end
  end

  def exportar_prepostulantes
    if @convocation.applications.empty?
      @error   = true 
      @message = "Las postulaciones no han sido cargadas aún"
      render :index and return
    end
    libro = RubyXL::Workbook.new
    libro.add_worksheet("Datos")
    hoja = libro.worksheets[0]
    hoja.insert_cell(0, 0, "Nombre y apellido")
    hoja.insert_cell(0, 1, "CUIL")
    hoja.insert_cell(0, 2, "Fecha nacimiento")
    @convocation.applications.each_with_index do |postulacion, i|
      hoja.insert_cell(i+1, 0, postulacion.applicant.apellidos_nombres)
      hoja.insert_cell(i+1, 1, postulacion.applicant.cuil)
      hoja.insert_cell(i+1, 2, postulacion.applicant.fecha_nacimiento.to_s)
    end
    file_name = "#{Rails.root}/tmp/post_#{@convocation.nombre}.xlsx"
    libro.write(file_name)
    @convocation.update(estado: Convocation::EVALUACION_MINISTERIO)
    send_file file_name
  end

  def html_prepostulantes_evaluados
    render 'carga_archivo_prepostulantes_evaluados'
  end

  def importar_prepostulantes_evaluados
    if params[:file]
      @convocation.importar_prepostulantes_evaluados(params[:file])
      render "applications/import_finished"    
    else
      render "applicants/import_fail"
    end
  end

  private

    def set_convocation
      @convocation = Convocation.find(params[:id])
    end

    def convocation_params
      params.require(:convocation).permit(:fecha_limite, :fecha_inicio, :nombre)
    end

    def resultados_as_json
      json = {}
      adjudicados = []
      rechazados = []
      @resultados[:adjudicados].each do |ad| 
        adjudicados << {
          nombre: ad.applicant.to_s,
          empresa: ad.organization.to_s
        }        
      end
      @resultados[:rechazados].each do |ad| 
        rechazados << {
          nombre: ad.applicant.to_s,
          empresa: ad.organization.to_s
        }        
      end
      json[:rechazados] = rechazados
      json[:adjudicados] = adjudicados
      json
    end
end

app/helpers/convocations_helper.rb
module ConvocationsHelper
end

app/views/convocations/_form.html.erb
<%= form_for(@convocation) do |f| %>
  <% if @convocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@convocation.errors.count, "error") %> prohibited this convocation from being saved:</h2>

      <ul>
      <% @convocation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="col-md-6">
    <div class="form-group">
      <%= f.label :nombre, class: 'control-label' %><br>
      <%= f.text_field :nombre, class: 'form-control' %>
    </div>
    <div class="form-group">
      <div class="form-inline"> <!-- Para que salgan en la misma linea los selects -->
        <%= f.label :fecha_inicio, "Fecha de inicio:", class: 'control-label' %><br>
        <%= f.date_select :fecha_inicio, {start_year: 1900, end_year: 2050}, {class: "form-control", layout: :inline, inline: true } %>
      </div>
    </div>

    <div class="form-group">
      <div class="form-inline"> <!-- Para que salgan en la misma linea los selects -->
        <%= f.label :fecha_limite, "Fecha límite:", class: 'control-label' %><br>
        <%= f.date_select :fecha_limite, {start_year: 1900, end_year: 2050}, {class: "form-control", layout: :inline, inline: true } %>
      </div>
    </div>
    <div class="form-group">
      <div class="actions">
        <%= f.submit "Guardar", class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/convocations/carga_archivo_prepostulantes_evaluados.html.erb
<h1>Carga de postulantes evaluadas</h1>
<div class="form-group">
  <label for="convocation" class="control-label">Convocatoria:</label>
  <input name="convocation" type="text" value="<%= @convocation.to_s %>" class="form-control" disabled>
</div>
<div>
  <%= form_tag importar_prepostulantes_evaluados_convocation_path, multipart: true do %>
    <label class="btn btn-default btn-file">
      Elegir archivo<%= file_field_tag :file, class: 'hidden' %>
    </label>
    <%= submit_tag "Importar", class: 'btn btn-success', id: 'importar', disabled: true %>
    <span style="margin-left: 10px" id="nombre-archivo"></span>
  <% end %>
</div>

app/views/convocations/carga_postulaciones.html.erb
<h1>Carga de postulaciones</h1>
<div class="form-group">
  <label for="convocation" class="control-label">Convocatoria:</label>
  <input name="convocation" type="text" value="<%= @convocation.to_s %>" class="form-control" disabled>
</div>
<div>
  <%= form_tag import_applications_convocation_path, multipart: true do %>
    <label class="btn btn-default btn-file">
      Elegir archivo<%= file_field_tag :file, class: 'hidden' %>
    </label>
    <%= submit_tag "Importar", class: 'btn btn-success', disabled: true, id: 'importar' %>
    <span style="margin-left: 10px" id="nombre-archivo"></span>
  <% end %>
</div>

app/views/convocations/edit.html.erb
<h1>Editing convocation</h1>

<%= render 'form' %>

<%= link_to 'Show', @convocation %> |
<%= link_to 'Back', convocations_path %>

app/views/convocations/index.html.erb
<h1>Convocatorias</h1>

<% if @error %>
  <p style="color:red"><%= @message %></p>
<% end %>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Fecha limite</th>
      <th>Fecha inicio</th>
      <th>Nombre</th>
      <th>Estado</th>
      <th>Acciones</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @convocations.each do |convocation| %>
      <tr>
        <td><%= convocation.fecha_limite %></td>
        <td><%= convocation.fecha_inicio %></td>
        <td><%= convocation.nombre %></td>
        <td>
        <%= badge_status(!convocation.cerrada?) %><%= convocation.estado_to_human %><span></td>
        <% if !convocation.cerrada? %>
        <td><%= link_to 'Importar pre-postulantes', carga_postulaciones_convocation_path(convocation) %></td>
        <td><%= link_to("Exportar pre-postulantes", exportar_prepostulantes_convocation_path(convocation), target: '_self') %></td>
        <td><%= link_to 'Importar pre-post. evaluados', html_prepostulantes_evaluados_convocation_path(convocation) %></td>
        
          <td><%= link_to 'Sortear', make_draw_convocation_path(convocation) %></td>
        <% end %>
        <td><%= link_to 'Mostrar', convocation %></td>
        <% if convocation.cerrada? %>
          <td><%= link_to 'Ver resultados', results_convocation_path(convocation) %></td>
        <% end %>
        <% if !convocation.cerrada? %>
          <td><%= link_to 'Editar', edit_convocation_path(convocation) %></td> 
        <% end %>
        <% if !convocation.cerrada? %>
          <td><%= link_to 'Borrar', convocation, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

 <!-- render page links in the view: -->
  <div class="flickr_pagination col-md-12">
    <%= will_paginate @convocations %>
  </div>
<br>

<%= link_to 'Nueva convocatoria', new_convocation_path, class: 'btn btn-default' %>

app/views/convocations/make_draw.html.erb
<div class="container">
  <h1>Ejecutar sorteo</h1>

  <% if @error %>
    <p style="color:red"><%= @message %></p>
  <% end %>

  <% if @convocation  %>
    <input class="form-control" type="text" disabled value="<%= @convocation.nombre %>">
    <input type="hidden" value="<%= @convocation.id %>">
    <br>
    <%= label :organization, 'Empresa' %>
    <%= select_tag "organization", 
                    options_from_collection_for_select(Organization.all, :id, :nombre), class: 'form-control',
                    disabled: @convocation.cerrada? %>
  <% end %>
  <br>
  <button id="realizar_sorteo" class="btn btn-success" <%= "disabled" if @convocation.cerrada? %>>
    Realizar sorteo
  </button>
  <div class="row <%= "hidden" if @convocation.cerrada? %>">
    <h3>Postulaciones</h3>
    <table id="postulantes" class="table col-md-8 hidden">
      <thead>
        <tr>
          <th>Postulante</th>
          <th>Empresa</th>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
    <div id="adjudicados" class="col-md-6 hidden">
      <h2 style="color:green">Adjudicados</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Postulante</th>
            <th>Empresa</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
    <div id="rechazados" class="col-md-6 hidden">
      <h2 style="color:red">Rechazados</h2>
      <table class="table ">
        <thead>
          <tr>
            <th>Postulante</th>
            <th>Empresa</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
  <div style="margin-top: 10px">
    <%= link_to("Volver", convocations_path, class: 'btn btn-primary') %>
  </div>
</div>

app/views/convocations/new.html.erb
<h1>Nueva convocatoria</h1>

<%= render 'form' %>

<div class="col-md-12" >
  <%= link_to 'Volver', convocations_path %>
</div>

app/views/convocations/results.html.erb
<div class="container">

  <div class="row">
    <% if @convocation  %>
      <h3 for="convocation">Convocatoria</h3>
      <input name="convocation" class="form-control" type="text" disabled value="<%= @convocation.nombre %>">
      <input type="hidden" value="<%= @convocation.id %>">
    <% end %>
    <br>
    <div class="pull-left">
    <a id="mail_beneficiarios" class="btn btn-success">Enviar mails a adjudicados</a>
    </div>
    <div>
      <a style="margin-left: 10px" id="mail_empresas" class="btn btn-primary">Enviar mails a empresas</a>
    </div>
  </div>

  <br>
  <div class="row">
    <div id="adjudicados" class="col-md-7 ">
      <h2 style="color:green">Adjudicados</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Postulante</th>
            <th>Empresa</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @resultados[:adjudicados].each do |a| %>
            <tr>
              <td><%= a.applicant %></td>
              <td><%= a.organization %></td>
              <td><%= link_to "Imprimir carta", carta_beneficiario_path(a), target: "_blank" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div id="rechazados" class="col-md-5 ">
      <h2 style="color:red">Rechazados</h2>
      <table class="table ">
        <thead>
          <tr>
            <th>Postulante</th>
            <th>Empresa</th>
          </tr>
        </thead>
        <tbody>
          <% @resultados[:rechazados].each do |a| %>
            <tr>
              <td><%= a.applicant %></td>
              <td><%= a.organization %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div>
      <h2 style="color:red">Empresas con adjudicaciones</h2>
      <table class="table ">
        <thead>
          <tr>
            <th>Empresa</th>
            <th>Cuit</th>
            <th>Imprimir carta</th>
          </tr>
        </thead>
        <tbody>
          <% @convocation.empresas_con_adjudicaciones.each do |org| %>
            <tr>
              <td><%= org.nombre %></td>
              <td><%= org.cuit %></td>
              <td><%= link_to "Carta" , carta_empresa_path(@convocation, org), target: '_blank' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/convocations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha limite:</strong>
  <%= @convocation.fecha_limite %>
</p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @convocation.fecha_inicio %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @convocation.nombre %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @convocation.estado_to_human %>
</p>


<% if @convocation.cerrada? %>
  <%= link_to 'Ver resultados', results_convocation_path(@convocation) %> | 
<% end %>
<%= link_to 'Editar', edit_convocation_path(@convocation) %> |
<%= link_to 'Volver', convocations_path %>


<h3>Postulaciones</h3>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Apellido y nombre</th>
      <th>Empresa</th>
      <th>Estado</th>
    </tr>
  </thead>
  <tbody>
    <% @convocation.applications.each do |a| %>
      <tr>
        <td><%= a.to_s %></td>
        <td><%= a.organization %></td>
        <td><%= a.estado_to_human %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h3>Empresas suscritas</h3>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cuit</th>
      <th>Cantidad personal</th>
      <th colspan="1"></th>
    </tr>
  </thead>
  <tbody>
    <% @convocation.organizations.each do |org| %>
      <tr>
        <td><%= org.to_s %></td>
        <td><%= org.cuit %></td>
        <td><%= org.cantidad_personal %></td>
        <td>
          <% if @convocation.algun_beneficiario_asignado?(org) %>
            <%= link_to "Carta" , carta_empresa_path(@convocation, org), target: '_blank' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>