config/routes.rb
Rails.application.routes.draw do

  resources :convocations do
    member do 
      get  'cargar-postulaciones'    => 'convocations#cargar_postulaciones',              as: 'carga_postulaciones'
      post 'importar-postulaciones' => 'convocations#importar_postulaciones',            as: 'import_applications'
      get  'exportar-prepostulantes' => 'convocations#exportar_prepostulantes',           as: 'exportar_prepostulantes'
      get  'ipe/html'                => 'convocations#html_prepostulantes_evaluados',     as: 'html_prepostulantes_evaluados'
      post 'ipe'                     => 'convocations#importar_prepostulantes_evaluados', as: 'importar_prepostulantes_evaluados'
      get "make"       => "convocations#make_draw", as: 'make_draw'
      get "results"    => "convocations#results"
      post 'sendmails' => 'convocations#send_mails'  
      post 'sendorganizationsmails' => 'convocations#send_mails_to_organizations'
    end
    collection do 
      get 'findapplications' => 'convocations#find_applications'
      post 'make'            => 'convocations#make_draw!'
    end
  end

  devise_for :users
  root to: "dashboard#index"

  get 'beneficiarios/:id' => 'applications#carta_beneficiario', as: :carta_beneficiario

  get 'convocations/:id/organization/:id_empresa' => 'convocations#carta_empresa', as: :carta_empresa

  resources :applications do
    collection do
      get 'full' => 'applications#full', as: 'full_application'
    end
  end

  resources :organizations

  resources :applicants do
    collection do
      post :import
    end
  end

  resources :departaments

end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id                :integer          not null, primary key
#  cuit              :string(255)
#  codigo_actividad  :string(15)
#  cantidad_personal :integer
#  calle             :string(255)
#  nro               :string(255)
#  localidad         :string(255)
#  telefono          :string(255)
#  fax               :string(255)
#  email             :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  nombre            :string(255)
#  departament_id    :integer
#  domicilio         :string(255)
#

class Organization < ActiveRecord::Base
  has_many :applications
  accepts_nested_attributes_for :applications 
  
  belongs_to :departament
  
  validates_presence_of :nombre, :cuit, :codigo_actividad, :cantidad_personal, :email
  validates_uniqueness_of :cuit

  def important_data
    "#{nombre}, CUIT: #{cuit}"
  end

  def vacantes
    return 1 if cantidad_personal.zero?
    cantidad_personal*2
  end

  def to_s
    important_data
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all.order('nombre').paginate(:page => params[:page], :per_page => 15)
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Empresa creada correctamente.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Empresa actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Empresa eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:nombre, :cuit, :codigo_actividad, :cantidad_personal, :calle, :nro, :localidad, :telefono, :fax, :email, :departament_id)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div class="alert fade in alert-error" id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> impide que los datos sean salvados:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6" >
    <span>Nombre de la empresa como figura en AFIP</span>
    <div class="form-group">
      <%= f.label :nombre, 'Razón Social', class: 'control-label' %><br>
      <%= f.text_field :nombre, class: 'form-control' %>
    </div>
    <div class="form-group required">
      <%= f.label :cuit, 'C.U.I.T (sin guiones ni puntos) ' , for: 'CUIT', class: 'control-label' %><br>
      <%= f.text_field :cuit, class: 'form-control' %>
    </div>
    <div class="form-group required">
      <%= f.label :codigo_actividad, 'Código Actividad (Código CIU AFIP) ', for: 'codigo_actividad', class: 'control-label' %>
      <%= link_to 'Consular códigos', "https://servicios1.afip.gob.ar/genericos/nomencladorActividades/index.aspx", target: "_blank" %> 
      <br>
      <%= f.text_field :codigo_actividad, class: 'form-control' %>
    </div>
    <div class="form-group required">
      <%= f.label :cantidad_personal, 'Cantidad de personal ', for: 'cantidad_personal', class: 'control-label' %><br>
      <%= f.number_field :cantidad_personal, class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-6" >
    <span>Domicilio legal de la empresa</span>
    <div class="form-group required">
      <%= f.label :departament_id, "Departamento ", class: 'control-label' %><br>
      <%= f.select :departament_id, options_from_collection_for_select(Departament.all, :id, :nombre), {selected: @organization.departament, prompt: 'Seleccione el departamento'}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :calle,'Calle', for: 'calle', class: 'control-label' %><br>
      <%= f.text_field :calle, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :nro, 'Nro.', for: 'nro', class: 'control-label' %><br>
      <%= f.text_field :nro, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :localidad, 'Localidad', for: 'localidad', class: 'control-label' %><br>
      <%= f.text_field :localidad, class: 'form-control' %>
    </div>
    <div class="form-group">
      
    </div>
    <div class="form-group">
      <%= f.label :telefono, 'Teléfono', for: 'telefono', class: 'control-label' %><br>
      <%= f.text_field :telefono, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :fax, 'FAX', for: 'fax', class: 'control-label' %><br>
      <%= f.text_field :fax, class: 'form-control' %>
    </div>
    <div class="form-group required">
      <%= f.label :email, 'Correo electrónico ', for: 'email', class: 'control-label' %><br>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <div class="actions">
        <%= f.submit 'Guardar', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<div class="col-md-12" >
  <%= link_to 'Mostrar', @organization %> |
  <%= link_to 'Volver', organizations_path %>
  <br>
</div>

app/views/organizations/index.html.erb
<h1>Empresas</h1>
<div class="col-md-12" >
  <table id="organizations-list" class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>Razon Social</th>
        <th>CUIT</th>
        <th>Codigo actividad</th>
        <th>Cantidad personal</th>
        <th>Calle</th>
        <th>Nro</th>
        <th>Localidad</th>
        <th>Telefono</th>
        <th>Fax</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @organizations.each do |organization| %>
        <tr>
          <td><%= organization.nombre %></td>
          <td><%= organization.cuit %></td>
          <td><%= organization.codigo_actividad %></td>
          <td><%= organization.cantidad_personal %></td>
          <td><%= organization.calle %></td>
          <td><%= organization.nro %></td>
          <td><%= organization.localidad %></td>
          <td><%= organization.telefono %></td>
          <td><%= organization.fax %></td>
          <td><%= organization.email %></td>
          <td><%= link_to 'Mostrar', organization %></td>
          <td><%= link_to 'Editar', edit_organization_path(organization) %></td>
          <td><%= link_to 'Eliminar', organization, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
   <!-- render page links in the view: -->
  <div class="flickr_pagination col-md-12">
    <%= will_paginate @organizations %>
  </div>
</div>
<br>

<%= link_to 'Agregar Empresa', new_organization_path, class: 'btn btn-primary' %>

app/views/organizations/new.html.erb
<h1>Nueva empresa</h1>

<%= render 'form' %>

<div class="col-md-12" >
  <%= link_to 'Volver', organizations_path %>
</div>

app/views/organizations/show.html.erb
<div class="col-md-12" >
  <p>
    <strong>Razón social:</strong>
    <%= @organization.nombre %>
  </p>
  <p>
    <strong>CUIT:</strong>
    <%= @organization.cuit %>
  </p>

  <p>
    <strong>Código actividad:</strong>
    <%= @organization.codigo_actividad %>
  </p>

  <p>
    <strong>Cantidad de personal:</strong>
    <%= @organization.cantidad_personal %>
  </p>

  <p>
    <strong>Calle:</strong>
    <%= @organization.calle %>
  </p>

  <p>
    <strong>Nro:</strong>
    <%= @organization.nro %>
  </p>

  <p>
    <strong>Localidad:</strong>
    <%= @organization.localidad %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= @organization.telefono %>
  </p>

  <p>
    <strong>Fax:</strong>
    <%= @organization.fax %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @organization.email %>
  </p>
</div>
<div class="col-md-12" >
  <hr>
  <%= link_to 'Editar', edit_organization_path(@organization) %> |
  <%= link_to 'Volver', organizations_path %>
  <br>
</div>