config/routes.rb
Rails.application.routes.draw do

  resources :convocations do
    member do 
      get  'cargar-postulaciones'    => 'convocations#cargar_postulaciones',              as: 'carga_postulaciones'
      post 'importar-postulaciones' => 'convocations#importar_postulaciones',            as: 'import_applications'
      get  'exportar-prepostulantes' => 'convocations#exportar_prepostulantes',           as: 'exportar_prepostulantes'
      get  'ipe/html'                => 'convocations#html_prepostulantes_evaluados',     as: 'html_prepostulantes_evaluados'
      post 'ipe'                     => 'convocations#importar_prepostulantes_evaluados', as: 'importar_prepostulantes_evaluados'
      get "make"       => "convocations#make_draw", as: 'make_draw'
      get "results"    => "convocations#results"
      post 'sendmails' => 'convocations#send_mails'  
      post 'sendorganizationsmails' => 'convocations#send_mails_to_organizations'
    end
    collection do 
      get 'findapplications' => 'convocations#find_applications'
      post 'make'            => 'convocations#make_draw!'
    end
  end

  devise_for :users
  root to: "dashboard#index"

  get 'beneficiarios/:id' => 'applications#carta_beneficiario', as: :carta_beneficiario

  get 'convocations/:id/organization/:id_empresa' => 'convocations#carta_empresa', as: :carta_empresa

  resources :applications do
    collection do
      get 'full' => 'applications#full', as: 'full_application'
    end
  end

  resources :organizations

  resources :applicants do
    collection do
      post :import
    end
  end

  resources :departaments

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Primer Empleo Corrientes</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <%= class_active_if_controller("dashboard") %>>
          <a href="/">Dashboard <span class="sr-only">(current)</span></a>
        </li>
        <li <%= class_active_if_controller("applicants") %>>
          <%= link_to "Postulantes", applicants_path %>
        </li>
        <li <%= class_active_if_controller("organizations") %>>
          <%= link_to "Empresas", organizations_path %>
        </li>
        <li <%= class_active_if_controller("applications") %>>
          <%= link_to "Postulaciones", applications_path %>
        </li>
        <li <%= class_active_if_controller("draws") %>>
          <%= link_to "Sorteos", draws_path %>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("logout", destroy_user_session_path, method: :delete) %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation.html.erb
<!-- # navigation styled for Bootstrap 3.0 -->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>" title="Peteíha Trabajo">
        <i class="fa fa-cogs"></i>
        <span aria-hidden="true"> Peteíha Trabajo</span>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
       <%= render 'layouts/navigation_links' %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to " #{current_user.email}", destroy_user_session_path, :method=>'delete', class: "navbar-link fa fa-user", title: "&nbsp; Cerrar sesión" %></a></li>
      </ul>
      <% end %>
    </div>


  </div>
</nav>
<!-- Navegación -->

<!-- /Navegación -->

app/views/layouts/_navigation_links.html.erb
<!-- add navigation links to this file -->
<li <%= class_active_if_controller("dashboard") %>>
  <%= link_to 'Inicio',  root_path %>
</li>
<% if user_signed_in? %>
  <li class="dropdown <%= class_active_if_controller("applicants") %>">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="fa fa-user"></span> Postulantes <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to ' Nuevo Postulante', new_applicant_path, class: 'fa fa-user' %></li>
      <li class="divider"></li>
      <li><%= link_to ' Listado Postulantes', applicants_path, class: 'fa fa-list' %></li>

    </ul>
  </li>
  <li class="dropdown <%= class_active_if_controller("organizations") %>"><a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="fa fa-building-o">
    </span> Empresas<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><%= link_to ' Nueva Empresa', new_organization_path, class: 'fa fa-building-o' %></li>
        <li class="divider"></li>
        <li><%= link_to ' Listado Empresas',organizations_path, class: "fa fa-list" %></li>
    </ul>
  </li>
  <li class="dropdown <%= class_active_if_controller("applications") %>"><a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="fa fa-inbox"></span> Postulaciones <span class="caret"></span></a>
      <ul class="dropdown-menu"> 
        <li><%= link_to ' Nueva Postulación Completa', full_application_applications_path, class: 'fa fa-id-card-o' %></li>
        <li><%= link_to ' Nueva Postulación', new_application_path, class: 'fa fa-inbox' %></li>
        <li class="divider"></li>
        <li><%= link_to ' Listado Postulaciones',applications_path, class: "fa fa-list" %></li>
      </ul>
  </li>
  <li class="dropdown <%= class_active_if_controller("convocations") %>" >
    <%= link_to " Convocatorias", convocations_path, class: 'fa fa-flag-checkered ' %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Peteíha Trabajo" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Peteíha Trabajo" %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= favicon_link_tag 'LogoPT.ico' %>
    <% if user_signed_in? %>
      <%= render 'layouts/navigation' %>
    <% end %>
 </header>
  <main role="main">
     <%= render 'layouts/messages' %>
     <div class="container">
      <%= yield %>
     </div>
    <div class="container">
      <br>
      <hr>
      <br>
    </div> 
  </main>
 
  <!-- Pie --> 
  <footer class="footer">
    <div class="container">
      <ul class="nav navbar-nav pull-left">
         <li><a href="/" class="fa fa-cogs"> Peteíha Trabajo Admin - <time datetime="2017-01-09">2017</time></a></li>
         <li><%= link_to ' Facebook', "https://web.facebook.com/peteihatrabajo/", class: "fa fa-facebook-official", target: "_blank" %></li>
         <li><%= link_to ' Contacto',  "mailto:peteihatrabajo@empleo.corrientes.gov.ar", class: "fa fa-envelope-o", target: "_blank" %></li>
      </ul>
    </div>
  </footer>
</body>
</html>